backend:
  name: git-gateway
  branch: master

media_folder: 'assets/uploads'

collections:
  - name: 'post'
    label: 'Peula'
    folder: '_posts/'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: 'Title', name: 'title', widget: 'string'}
