backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

collections:
  - name: 'peula'
    label: 'פעולה'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'כותרת הפעולה', name: 'title', widget: 'string' }
      - { label: 'תקציר הפעולה', name: 'desc', widget: 'string' }
      - { label: 'משך הפעולה (במילים)', name: 'length', widget: 'string' }
      - { label: 'תאריך פרסום', name: 'date', widget: 'datetime' }
      - label: "מטרות"
        name: "goals"
        widget: "list"
        field: {label: 'מטרה', name: 'goal', widget: 'string'}
      - label: "מתודות"
        name: "course"
        widget: "list"
        field: {label: 'מתודה', name: 'method', widget: 'markdown'}
      - label: "ציוד"
        name: "equipment"
        widget: "list"
        field: {label: 'ציוד', name: 'equipment', widget: 'string'}
      - label: "נושאים"
        name: "categories"
        widget: "list"
        field: {label: 'נושא', name: 'category', widget: 'string'}
      - label: "תגיות"
        name: "tags"
        widget: "list"
        field: {label: 'תגית', name: 'tag', widget: 'string'}
      # - { label: 'Body', name: 'body', widget: 'markdown' }

# layout
# title
# desc
# date:   2020-09-21 17:41
# categories
# age
# goals
# course
# length
# tags
# equipment
